### PR TITLE
BIM_Specs: Markdown restructure

### PR DESCRIPTION
**Pull request by luzpaz**
* Moved URLs out of tables  
* Added Emojis for visual simplification  
* Reformatted table text for clarity in editor  
* Updated Table template  
* Added Legend to end of file  

**Note:** Many of the IFC urls are broken and need to be updated

### CODE REVIEW

**Comment by luzpaz** [comment]
Preview: https://github.com/luzpaz/FreeMVD_WorkFlow/blob/bim-specs-markdown/BIM_Specifications.md

Edit: Don't forget to test any broken URLS against the current BIM_Specification.md in master.

**Comment by luzpaz** [comment]
ping @yorikvanhavre, @Moult

**Comment by luzpaz** [comment]
bump

**Comment by Moult** [comment]
This is kinda Yoriks initiative I think he should approve PRs :) unless he's ok with me doing so

**Comment by luzpaz** [comment]
@yorikvanhavre ping

**Comment by yorikvanhavre** [comment]
oops sorry guys, missed this one... Looks good to me!

**Pull request merged**
